Class {
	#name : #QueuedBlueRun,
	#superclass : #JenkinsURL,
	#instVars : [
		'_actions',
		'_enQueueTime',
		'_result',
		'_runSummary',
		'_changeSet',
		'_name',
		'_type',
		'_endTime',
		'_causeOfBlockage',
		'_durationInMillis',
		'_artifactsZipFile',
		'_estimatedDurationInMillis',
		'_organization',
		'__links',
		'_startTime',
		'_pipeline',
		'_description',
		'_state',
		'_causes',
		'_id',
		'_replayable',
		'_queueId'
	],
	#category : #'GToolkit-Releaser-Jenkins-Generated-IoJenkinsBlueoceanServiceEmbeddedRest'
}
