Class {
	#name : #WfJobRunStageStageFlowNodeConsoleStageFlowNodeConsoleStageFlowNodeConsole,
	#superclass : #JenkinsWFAPI,
	#instVars : [
		'startTimeMillis',
		'name',
		'pauseDurationMillis',
		'status',
		'stageFlowNodes',
		'execNode',
		'durationMillis',
		'hasMore',
		'nodeStatus',
		'length',
		'consoleUrl',
		'nodeId',
		'text'
	],
	#category : #'GToolkit-Releaser-Jenkins-Generated-Wfapi'
}
