"
I store metadata for this package used by various other tools.
"
Class {
	#name : #ManifestGToolkitReleaserIcebergExtensions,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Releaser-IcebergExtensions'
}

{ #category : #'meta-data' }
ManifestGToolkitReleaserIcebergExtensions class >> description [ 
	^ 'I provide extensions for Iceberg classes to make easier to understand the model of Iceberg from within the inspector.'
]
