"
I store metadata for this package used by various other tools.
"
Class {
	#name : #ManifestGToolkitReleaserBaselineModel,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Releaser-BaselineModel'
}

{ #category : #'as yet unclassified' }
ManifestGToolkitReleaserBaselineModel class >> decription [
	^ 'I contain a model for capturing Metacello baselines and dependencies between baselines.'
]
