"
I store metadata for this package used by various other tools.
"
Class {
	#name : #ManifestGToolkitReleaserBaselineModelExamples,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Releaser-BaselineModel-Examples'
}

{ #category : #'meta-data' }
ManifestGToolkitReleaserBaselineModelExamples class >> description [ 
	^ 'I provide examples for the baseline model used for documentation and testing.'
]
