"
I store metadata for this package used by various other tools.


"
Class {
	#name : #ManifestGToolkitReleaserBaselineModelMinimalIceberg,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Releaser-BaselineModel-MinimalIceberg'
}

{ #category : #'meta-data' }
ManifestGToolkitReleaserBaselineModelMinimalIceberg class >> description [ 
	^ 'I provide a very simple implementation of in-memory Iceberg repository. I exist for supporting example for documentation as the package Iceberg-Memory is not loaded by defaut with Iceberg.'
]
